In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)
a
a.size

5

In [5]:
a.ndim

1

In [6]:
a.dtype

dtype('int32')

In [7]:
a.shape

(5,)

In [8]:
a + 10

array([11, 12, 13, 14, 15])

In [9]:
a-10
a*10
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [20]:
b = np.array([6,7,8,9,10])
b


array([ 6,  7,  8,  9, 10])

In [21]:
b + 10
b

array([ 6,  7,  8,  9, 10])

In [22]:
a + b

array([ 7,  9, 11, 13, 15])

In [23]:
a * b

array([ 6, 14, 24, 36, 50])

In [24]:
a - b

array([-5, -5, -5, -5, -5])

In [27]:
c = np.array([0,1,2,3,4,5], dtype=bool )
c

array([False,  True,  True,  True,  True,  True])

In [28]:
d = np.array([0,1,2,3,4,5],dtype=complex)
d

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])